### ISSUE TITLE
Unable to connect to Ollama container.

### ISSUE THREAD

**Issue by Artalius** [mxyng/discollama#22]
I have Ollama running in a separate container (from a neighboring folder) on PhotonOS VM
along with setting both Ollama and Discollama to run on the same docker network (lixi-net)

The below log shows that the connection to the Discord app is working, and the Bot's presence is responsive to Discollama along with the `is typing...` and `Ask me anything!` prompts.

I would appreciate any feedback or pointers to documentation.
`- OLLAMA_HOST=http://ollama` is set since leaving to default was not working either, and this closely matches the open-webui setting

**EDIT** Solved: feel free to refer to the YML files below

- `Ollama` `hostname: ollama`
- `DiscOllama` `- OLLAMA_HOST=http://ollama:11434` and remove `- OLLAMA_PORT`

<details><summary>Ollama YML</summary>

```yml
services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - 11434:11434
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # optional but required for Docker integration
      - /root/ollama/ollama/data:/root/.ollama
    labels:
      # For the FLAME docker
...
      # For HOMEPAGE Docker to read via .sock.
...
    pull_policy: always
    tty: true
    networks:
      - lixi-net
    hostname: ollama
    restart: unless-stopped

  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:latest
    container_name: open-webui
    ports:
      - 3000:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # optional but required for Docker integration
      - /root/ollama/open-webui/data:/app/backend/data
    labels:
      # For the FLAME docker
...
      # For HOMEPAGE Docker to read via .sock.
...
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - ollama
    pull_policy: always
    networks:
      - lixi-net
    restart: unless-stopped

volumes:
  ollama: {}
  open-webui: {}

networks:
  lixi-net:
    driver: bridge
    name: lixi-net
```

</details>

<details><summary>Discollama YML</summary>

```yml
version: "3.3"
services:
  discollama:
    image: ghcr.io/mxyng/discollama:main
    container_name: discollama
    build:
      context: .
      dockerfile: Dockerfile
    command: ['--redis-host', 'redis']
    environment:
      - DISCORD_TOKEN=MTIxxxxxxxxxxxxxxxxx.TOKEN.123456789012345
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_MODEL=llama3.2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # optional but required for Docker integration
    labels:
      # For the FLAME docker
...
      # For HOMEPAGE Docker to read via .sock.
...
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - lixi-net
    hostname: discollama
    restart: unless-stopped

  redis:
    image: redis/redis-stack-server:latest
    volumes:
      - /data
    ports:
      - 6379
    networks:
      - lixi-net
    restart: unless-stopped

networks:
  lixi-net:
    external: true
    name: lixi-net
```

</details>

<details><summary>Log (original symptoms)</summary>
<br>
<details><summary>Exception</summary>

```bash
2024-09-24T21:12:25.025564150Z 2024-09-24 21:12:25 INFO     discord.client logging in using static token
2024-09-24T21:12:25.798384435Z 2024-09-24 21:12:25 INFO     discord.gateway Shard ID None has connected to Gateway (Session ID: 1efe4bf1f3706f56982205df6c484296).
2024-09-24T21:12:27.806992159Z 2024-09-24 21:12:27 INFO     discord.discollama Ready! Invite URL: https://discord.com/oauth2/authorize?client_id=1288135504285532190&scope=bot&permissions=34359741440
2024-09-24T21:14:30.069483152Z 2024-09-24 21:14:30 ERROR    discord.client Ignoring exception in on_message
2024-09-24T21:14:30.069525011Z Traceback (most recent call last):
2024-09-24T21:14:30.069532833Z   File "/root/.cache/pypoetry/virtualenvs/discollama-_erODJfD-py3.11/lib/python3.11/site-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
2024-09-24T21:14:30.069539390Z     yield
2024-09-24T21:14:30.069545537Z   File "/root/.cache/pypoetry/virtualenvs/discollama-_erODJfD-py3.11/lib/python3.11/site-packages/httpx/_transports/default.py", line 377, in handle_async_request
2024-09-24T21:14:30.069551774Z     resp = await self._pool.handle_async_request(req)
2024-09-24T21:14:30.069557719Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-24T21:14:30.069563661Z   File "/root/.cache/pypoetry/virtualenvs/discollama-_erODJfD-py3.11/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
2024-09-24T21:14:30.069569847Z     raise exc from None
2024-09-24T21:14:30.069575709Z   File "/root/.cache/pypoetry/virtualenvs/discollama-_erODJfD-py3.11/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
2024-09-24T21:14:30.069581911Z     response = await connection.handle_async_request(
2024-09-24T21:14:30.069588250Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-24T21:14:30.069594197Z   File "/root/.cache/pypoetry/virtualenvs/discollama-_erODJfD-py3.11/lib/python3.11/site-packages/httpcore/_async/connection.py", line 99, in handle_async_request
2024-09-24T21:14:30.069600349Z     raise exc
2024-09-24T21:14:30.069606236Z   File "/root/.cache/pypoetry/virtualenvs/discollama-_erODJfD-py3.11/lib/python3.11/site-packages/httpcore/_async/connection.py", line 76, in handle_async_request
2024-09-24T21:14:30.069612349Z     stream = await self._connect(request)
2024-09-24T21:14:30.069618235Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-24T21:14:30.069624109Z   File "/root/.cache/pypoetry/virtualenvs/discollama-_erODJfD-py3.11/lib/python3.11/site-packages/httpcore/_async/connection.py", line 122, in _connect
2024-09-24T21:14:30.069630291Z     stream = await self._network_backend.connect_tcp(**kwargs)
2024-09-24T21:14:30.069636641Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-24T21:14:30.069642532Z   File "/root/.cache/pypoetry/virtualenvs/discollama-_erODJfD-py3.11/lib/python3.11/site-packages/httpcore/_backends/auto.py", line 30, in connect_tcp
2024-09-24T21:14:30.069661666Z     return await self._backend.connect_tcp(
2024-09-24T21:14:30.069667779Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-24T21:14:30.069675079Z   File "/root/.cache/pypoetry/virtualenvs/discollama-_erODJfD-py3.11/lib/python3.11/site-packages/httpcore/_backends/anyio.py", line 114, in connect_tcp
2024-09-24T21:14:30.069681294Z     with map_exceptions(exc_map):
2024-09-24T21:14:30.069687174Z   File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
2024-09-24T21:14:30.069693111Z     self.gen.throw(typ, value, traceback)
2024-09-24T21:14:30.069698939Z   File "/root/.cache/pypoetry/virtualenvs/discollama-_erODJfD-py3.11/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
2024-09-24T21:14:30.069705141Z     raise to_exc(exc) from exc
2024-09-24T21:14:30.069710909Z httpcore.ConnectError: All connection attempts failed
2024-09-24T21:14:30.069716846Z
2024-09-24T21:14:30.069722592Z The above exception was the direct cause of the following exception:
2024-09-24T21:14:30.069728621Z
2024-09-24T21:14:30.069734387Z Traceback (most recent call last):
2024-09-24T21:14:30.069740197Z   File "/root/.cache/pypoetry/virtualenvs/discollama-_erODJfD-py3.11/lib/python3.11/site-packages/discord/client.py", line 449, in _run_event
2024-09-24T21:14:30.069746301Z     await coro(*args, **kwargs)
2024-09-24T21:14:30.069752119Z   File "/mnt/discollama.py", line 109, in on_message
2024-09-24T21:14:30.069758000Z     async for part in self.generate(content, context):
2024-09-24T21:14:30.069764206Z   File "/mnt/discollama.py", line 131, in generate
2024-09-24T21:14:30.069770150Z     async for part in await self.ollama.generate(model=self.model, prompt=content, context=context, keep_alive=-1, stream=True):
2024-09-24T21:14:30.069776288Z   File "/root/.cache/pypoetry/virtualenvs/discollama-_erODJfD-py3.11/lib/python3.11/site-packages/ollama/_client.py", line 494, in inner
2024-09-24T21:14:30.069782351Z     async with self._client.stream(method, url, **kwargs) as r:
2024-09-24T21:14:30.069788231Z   File "/usr/local/lib/python3.11/contextlib.py", line 204, in __aenter__
2024-09-24T21:14:30.069794166Z     return await anext(self.gen)
2024-09-24T21:14:30.069800080Z            ^^^^^^^^^^^^^^^^^^^^^
2024-09-24T21:14:30.069805888Z   File "/root/.cache/pypoetry/virtualenvs/discollama-_erODJfD-py3.11/lib/python3.11/site-packages/httpx/_client.py", line 1628, in stream
2024-09-24T21:14:30.069812110Z     response = await self.send(
2024-09-24T21:14:30.069817880Z                ^^^^^^^^^^^^^^^^
2024-09-24T21:14:30.069823688Z   File "/root/.cache/pypoetry/virtualenvs/discollama-_erODJfD-py3.11/lib/python3.11/site-packages/httpx/_client.py", line 1674, in send
2024-09-24T21:14:30.069829726Z     response = await self._send_handling_auth(
2024-09-24T21:14:30.069835515Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-24T21:14:30.069848510Z   File "/root/.cache/pypoetry/virtualenvs/discollama-_erODJfD-py3.11/lib/python3.11/site-packages/httpx/_client.py", line 1702, in _send_handling_auth
2024-09-24T21:14:30.069854933Z     response = await self._send_handling_redirects(
2024-09-24T21:14:30.069861288Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-24T21:14:30.069867299Z   File "/root/.cache/pypoetry/virtualenvs/discollama-_erODJfD-py3.11/lib/python3.11/site-packages/httpx/_client.py", line 1739, in _send_handling_redirects
2024-09-24T21:14:30.069873496Z     response = await self._send_single_request(request)
2024-09-24T21:14:30.069881135Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-24T21:14:30.069887189Z   File "/root/.cache/pypoetry/virtualenvs/discollama-_erODJfD-py3.11/lib/python3.11/site-packages/httpx/_client.py", line 1776, in _send_single_request
2024-09-24T21:14:30.069893476Z     response = await transport.handle_async_request(request)
2024-09-24T21:14:30.069899341Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-24T21:14:30.069905428Z   File "/root/.cache/pypoetry/virtualenvs/discollama-_erODJfD-py3.11/lib/python3.11/site-packages/httpx/_transports/default.py", line 376, in handle_async_request
2024-09-24T21:14:30.069912239Z     with map_httpcore_exceptions():
2024-09-24T21:14:30.069919949Z   File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
2024-09-24T21:14:30.069930411Z     self.gen.throw(typ, value, traceback)
2024-09-24T21:14:30.069941309Z   File "/root/.cache/pypoetry/virtualenvs/discollama-_erODJfD-py3.11/lib/python3.11/site-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
2024-09-24T21:14:30.069951898Z     raise mapped_exc(message) from exc
2024-09-24T21:14:30.069962655Z httpx.ConnectError: All connection attempts failed
2024-09-24T21:15:36.566978267Z 2024-09-24 21:15:36 ERROR    discord.client Ignoring exception in on_message
2024-09-24T21:15:36.567025217Z Traceback (most recent call last):
2024-09-24T21:15:36.567033470Z   File "/root/.cache/pypoetry/virtualenvs/discollama-_erODJfD-py3.11/lib/python3.11/site-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
2024-09-24T21:15:36.567040070Z     yield
2024-09-24T21:15:36.567046000Z   File "/root/.cache/pypoetry/virtualenvs/discollama-_erODJfD-py3.11/lib/python3.11/site-packages/httpx/_transports/default.py", line 377, in handle_async_request
2024-09-24T21:15:36.567052526Z     resp = await self._pool.handle_async_request(req)
2024-09-24T21:15:36.567058485Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-24T21:15:36.567064538Z   File "/root/.cache/pypoetry/virtualenvs/discollama-_erODJfD-py3.11/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
2024-09-24T21:15:36.567070880Z     raise exc from None
2024-09-24T21:15:36.567076870Z   File "/root/.cache/pypoetry/virtualenvs/discollama-_erODJfD-py3.11/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
2024-09-24T21:15:36.567095886Z     response = await connection.handle_async_request(
2024-09-24T21:15:36.567101987Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-24T21:15:36.567107880Z   File "/root/.cache/pypoetry/virtualenvs/discollama-_erODJfD-py3.11/lib/python3.11/site-packages/httpcore/_async/connection.py", line 99, in handle_async_request
2024-09-24T21:15:36.567114146Z     raise exc
2024-09-24T21:15:36.567119905Z   File "/root/.cache/pypoetry/virtualenvs/discollama-_erODJfD-py3.11/lib/python3.11/site-packages/httpcore/_async/connection.py", line 76, in handle_async_request
2024-09-24T21:15:36.567126145Z     stream = await self._connect(request)
2024-09-24T21:15:36.567132100Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-24T21:15:36.567138006Z   File "/root/.cache/pypoetry/virtualenvs/discollama-_erODJfD-py3.11/lib/python3.11/site-packages/httpcore/_async/connection.py", line 122, in _connect
2024-09-24T21:15:36.567144188Z     stream = await self._network_backend.connect_tcp(**kwargs)
2024-09-24T21:15:36.567150240Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-24T21:15:36.567156566Z   File "/root/.cache/pypoetry/virtualenvs/discollama-_erODJfD-py3.11/lib/python3.11/site-packages/httpcore/_backends/auto.py", line 30, in connect_tcp
2024-09-24T21:15:36.567162671Z     return await self._backend.connect_tcp(
2024-09-24T21:15:36.567168532Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-24T21:15:36.567175792Z   File "/root/.cache/pypoetry/virtualenvs/discollama-_erODJfD-py3.11/lib/python3.11/site-packages/httpcore/_backends/anyio.py", line 114, in connect_tcp
2024-09-24T21:15:36.567182231Z     with map_exceptions(exc_map):
2024-09-24T21:15:36.567188106Z   File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
2024-09-24T21:15:36.567194070Z     self.gen.throw(typ, value, traceback)
2024-09-24T21:15:36.567199986Z   File "/root/.cache/pypoetry/virtualenvs/discollama-_erODJfD-py3.11/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
2024-09-24T21:15:36.567206206Z     raise to_exc(exc) from exc
2024-09-24T21:15:36.567211992Z httpcore.ConnectError: All connection attempts failed
2024-09-24T21:15:36.567217872Z
```

</details>

<details><summary>Direct cause</summary>

```bash
2024-09-24T21:15:36.567223700Z The above exception was the direct cause of the following exception:
2024-09-24T21:15:36.567229707Z
2024-09-24T21:15:36.567235402Z Traceback (most recent call last):
2024-09-24T21:15:36.567241229Z   File "/root/.cache/pypoetry/virtualenvs/discollama-_erODJfD-py3.11/lib/python3.11/site-packages/discord/client.py", line 449, in _run_event
2024-09-24T21:15:36.567247364Z     await coro(*args, **kwargs)
2024-09-24T21:15:36.567253160Z   File "/mnt/discollama.py", line 109, in on_message
2024-09-24T21:15:36.567259144Z     async for part in self.generate(content, context):
2024-09-24T21:15:36.567271802Z   File "/mnt/discollama.py", line 131, in generate
2024-09-24T21:15:36.567278031Z     async for part in await self.ollama.generate(model=self.model, prompt=content, context=context, keep_alive=-1, stream=True):
2024-09-24T21:15:36.567284184Z   File "/root/.cache/pypoetry/virtualenvs/discollama-_erODJfD-py3.11/lib/python3.11/site-packages/ollama/_client.py", line 494, in inner
2024-09-24T21:15:36.567290260Z     async with self._client.stream(method, url, **kwargs) as r:
2024-09-24T21:15:36.567296209Z   File "/usr/local/lib/python3.11/contextlib.py", line 204, in __aenter__
2024-09-24T21:15:36.567302301Z     return await anext(self.gen)
2024-09-24T21:15:36.567308127Z            ^^^^^^^^^^^^^^^^^^^^^
2024-09-24T21:15:36.567313925Z   File "/root/.cache/pypoetry/virtualenvs/discollama-_erODJfD-py3.11/lib/python3.11/site-packages/httpx/_client.py", line 1628, in stream
2024-09-24T21:15:36.567320129Z     response = await self.send(
2024-09-24T21:15:36.567325979Z                ^^^^^^^^^^^^^^^^
2024-09-24T21:15:36.567331866Z   File "/root/.cache/pypoetry/virtualenvs/discollama-_erODJfD-py3.11/lib/python3.11/site-packages/httpx/_client.py", line 1674, in send
2024-09-24T21:15:36.567337927Z     response = await self._send_handling_auth(
2024-09-24T21:15:36.567343781Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-24T21:15:36.567349671Z   File "/root/.cache/pypoetry/virtualenvs/discollama-_erODJfD-py3.11/lib/python3.11/site-packages/httpx/_client.py", line 1702, in _send_handling_auth
2024-09-24T21:15:36.567355837Z     response = await self._send_handling_redirects(
2024-09-24T21:15:36.567362547Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-24T21:15:36.567368507Z   File "/root/.cache/pypoetry/virtualenvs/discollama-_erODJfD-py3.11/lib/python3.11/site-packages/httpx/_client.py", line 1739, in _send_handling_redirects
2024-09-24T21:15:36.567374900Z     response = await self._send_single_request(request)
2024-09-24T21:15:36.567380810Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-24T21:15:36.567386669Z   File "/root/.cache/pypoetry/virtualenvs/discollama-_erODJfD-py3.11/lib/python3.11/site-packages/httpx/_client.py", line 1776, in _send_single_request
2024-09-24T21:15:36.567392983Z     response = await transport.handle_async_request(request)
2024-09-24T21:15:36.567398900Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-24T21:15:36.567404781Z   File "/root/.cache/pypoetry/virtualenvs/discollama-_erODJfD-py3.11/lib/python3.11/site-packages/httpx/_transports/default.py", line 376, in handle_async_request
2024-09-24T21:15:36.567410941Z     with map_httpcore_exceptions():
2024-09-24T21:15:36.567417098Z   File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
2024-09-24T21:15:36.567423039Z     self.gen.throw(typ, value, traceback)
2024-09-24T21:15:36.567428986Z   File "/root/.cache/pypoetry/virtualenvs/discollama-_erODJfD-py3.11/lib/python3.11/site-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
2024-09-24T21:15:36.567441213Z     raise mapped_exc(message) from exc
2024-09-24T21:15:36.567447225Z httpx.ConnectError: All connection attempts failed
```

</details>

<details><summary>Never Retrived</summary>

```bash
2024-09-24T21:31:09.723002111Z Task exception was never retrieved
2024-09-24T21:31:09.723052088Z future: <Task finished name='Task-20' coro=<Discollama.thinking() done, defined at /mnt/discollama.py:117> exception=NotFound('404 Not Found (error code: 10008): Unknown Message')>
2024-09-24T21:31:09.723062437Z Traceback (most recent call last):
2024-09-24T21:31:09.723068493Z   File "/mnt/discollama.py", line 125, in thinking
2024-09-24T21:31:09.723074867Z     await message.remove_reaction('🤔', self.discord.user)
2024-09-24T21:31:09.723081513Z   File "/root/.cache/pypoetry/virtualenvs/discollama-_erODJfD-py3.11/lib/python3.11/site-packages/discord/message.py", line 1299, in remove_reaction
2024-09-24T21:31:09.723087934Z     await self._state.http.remove_own_reaction(self.channel.id, self.id, emoji)
2024-09-24T21:31:09.723094268Z   File "/root/.cache/pypoetry/virtualenvs/discollama-_erODJfD-py3.11/lib/python3.11/site-packages/discord/http.py", line 754, in request
2024-09-24T21:31:09.723100611Z     raise NotFound(response, data)
2024-09-24T21:31:09.723106494Z discord.errors.NotFound: 404 Not Found (error code: 10008): Unknown Message
````

</details>

</details>

**Comment by Artalius** [comment]
updated YAML for fixed hostnames (updated in OP)

Verify comms from DiscOllama to Ollama as below

```bash
~> docker exec -it discollama /bin/sh
~> hostname; echo; ping -c 1 ollama && echo;  nc -zv ollama 11434
discollama

PING ollama (192.168.192.2): 56 data bytes
64 bytes from 192.168.192.2: seq=0 ttl=64 time=0.096 ms

--- ollama ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.096/0.096/0.096 ms

ollama (192.168.192.2:11434) open
```
