### ISSUE TITLE
Unknown command "JSON.SET"

### ISSUE THREAD

**Issue by simonSlamka** [mxyng/discollama#5]
Hey,

Been getting `ResponseError` exceptions when calling ollama from Discord. I get a part of the generation, but when the message is about to be updated, I get the following:

```
Traceback (most recent call last):
  File "/home/sysop/discollama/venv/lib/python3.11/site-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/sysop/discollama/discollama.py", line 120, in on_message
    save_session(response, part)
  File "/home/sysop/discollama/discollama.py", line 63, in save_session
    redis.json().set(f'ollama:{response.id}', '$', {'context': context})
  File "/home/sysop/discollama/venv/lib/python3.11/site-packages/redis/commands/json/commands.py", line 253, in set
    return self.execute_command("JSON.SET", *pieces)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sysop/discollama/venv/lib/python3.11/site-packages/redis/client.py", line 536, in execute_command
    return conn.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sysop/discollama/venv/lib/python3.11/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
           ^^^^
  File "/home/sysop/discollama/venv/lib/python3.11/site-packages/redis/client.py", line 537, in <lambda>
    lambda: self._send_command_parse_response(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sysop/discollama/venv/lib/python3.11/site-packages/redis/client.py", line 513, in _send_command_parse_response
    return self.parse_response(conn, command_name, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sysop/discollama/venv/lib/python3.11/site-packages/redis/client.py", line 553, in parse_response
    response = connection.read_response()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sysop/discollama/venv/lib/python3.11/site-packages/redis/connection.py", line 524, in read_response
    raise response
redis.exceptions.ResponseError: unknown command `JSON.SET`, with args beginning with: `ollama:1164085331365203989`, `$`, `{"context": [29871, 13, 13, 3492, 526, 4485, 5667, 29892, 385, 14154, 564, 9102, 424, 29892, `, 
```

Repro is to create a venv using Python3.11, follow the installation, launch the bot, and on Discord, send a message where the bot is mentioned. The message is sent, but the first subsequent edit of the message to update its contents produces the above exception.

Any ideas?

Thanks a lot!

**Comment by mxyng** [comment]
The README is slightly out of date. Memory requires Redis and specifically Redis Stack for JSON support. If you use docker compose, it will deploy a python container for discollama and a redis stack container for storing history. I'll update the README.

**Comment by mxyng** [comment]
README has been updated. You can use docker compose to configure both discollama and redis stack
