### ISSUE TITLE
Shard ID None

### ISSUE THREAD

**Issue by Notplying** [mxyng/discollama#7]
After tagging in discord server gives 
Can't connect to the ollama server (in another conatiner), server is confirmed working, server can communicate with [Ollama Web UI](https://github.com/ollama-webui/ollama-webui), and [Discord AI Bot](https://github.com/mekb-turtle/discord-ai-bot).
```
discollama-main-discollama-1  | 2023-12-26 11:17:30 INFO     discord.client logging in using static token
discollama-main-discollama-1  | 2023-12-26 11:17:32 INFO     discord.gateway Shard ID None has connected to Gateway (Session ID: 331a82dfd8f92d83ae39f19e237ae188).
discollama-main-discollama-1  | 2023-12-26 11:17:34 INFO     root Ready! Invite URL: https://discord.com/oauth2/authorize?client_id=1186485943037870110&scope=bot&permissions=3072
discollama-main-discollama-1  | 2023-12-26 11:17:46 ERROR    discord.client Ignoring exception in on_message
discollama-main-discollama-1  | Traceback (most recent call last):
discollama-main-discollama-1  |   File "/root/.cache/pypoetry/virtualenvs/discollama-_erODJfD-py3.11/lib/python3.11/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
discollama-main-discollama-1  |     return await self._loop.create_connection(*args, **kwargs)
discollama-main-discollama-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
discollama-main-discollama-1  |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1085, in create_connection
discollama-main-discollama-1  |     raise exceptions[0]
discollama-main-discollama-1  |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1069, in create_connection
discollama-main-discollama-1  |     sock = await self._connect_sock(
discollama-main-discollama-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
discollama-main-discollama-1  |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 973, in _connect_sock
discollama-main-discollama-1  |     await self.sock_connect(sock, address)
discollama-main-discollama-1  |   File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 634, in sock_connect
discollama-main-discollama-1  |     return await fut
discollama-main-discollama-1  |            ^^^^^^^^^
discollama-main-discollama-1  |   File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 674, in _sock_connect_cb
discollama-main-discollama-1  |     raise OSError(err, f'Connect call failed {address}')
discollama-main-discollama-1  | ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 11434)
discollama-main-discollama-1  |
discollama-main-discollama-1  | The above exception was the direct cause of the following exception:
discollama-main-discollama-1  |
discollama-main-discollama-1  | Traceback (most recent call last):
discollama-main-discollama-1  |   File "/root/.cache/pypoetry/virtualenvs/discollama-_erODJfD-py3.11/lib/python3.11/site-packages/discord/client.py", line 441, in _run_event
discollama-main-discollama-1  |     await coro(*args, **kwargs)
discollama-main-discollama-1  |   File "/mnt/discollama.py", line 114, in on_message
discollama-main-discollama-1  |     async for buffer, part in buffered_generate_response(
discollama-main-discollama-1  |   File "/mnt/discollama.py", line 47, in buffered_generate_response
discollama-main-discollama-1  |     async for part in generate_response(prompt, context):
discollama-main-discollama-1  |   File "/mnt/discollama.py", line 38, in generate_response
discollama-main-discollama-1  |     async with session.post(
discollama-main-discollama-1  |   File "/root/.cache/pypoetry/virtualenvs/discollama-_erODJfD-py3.11/lib/python3.11/site-packages/aiohttp/client.py", line 1187, in __aenter__
discollama-main-discollama-1  |     self._resp = await self._coro
discollama-main-discollama-1  |                  ^^^^^^^^^^^^^^^^
discollama-main-discollama-1  |   File "/root/.cache/pypoetry/virtualenvs/discollama-_erODJfD-py3.11/lib/python3.11/site-packages/aiohttp/client.py", line 574, in _request
discollama-main-discollama-1  |     conn = await self._connector.connect(
discollama-main-discollama-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
discollama-main-discollama-1  |   File "/root/.cache/pypoetry/virtualenvs/discollama-_erODJfD-py3.11/lib/python3.11/site-packages/aiohttp/connector.py", line 540, in connect
discollama-main-discollama-1  |     proto = await self._create_connection(req, traces, timeout)
discollama-main-discollama-1  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
discollama-main-discollama-1  |   File "/root/.cache/pypoetry/virtualenvs/discollama-_erODJfD-py3.11/lib/python3.11/site-packages/aiohttp/connector.py", line 907, in _create_connection
discollama-main-discollama-1  |     _, proto = await self._create_direct_connection(req, traces, timeout)
discollama-main-discollama-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
discollama-main-discollama-1  |   File "/root/.cache/pypoetry/virtualenvs/discollama-_erODJfD-py3.11/lib/python3.11/site-packages/aiohttp/connector.py", line 1231, in _create_direct_connection
discollama-main-discollama-1  |     raise last_exc
discollama-main-discollama-1  |   File "/root/.cache/pypoetry/virtualenvs/discollama-_erODJfD-py3.11/lib/python3.11/site-packages/aiohttp/connector.py", line 1200, in _create_direct_connection
discollama-main-discollama-1  |     transp, proto = await self._wrap_create_connection(
discollama-main-discollama-1  |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
discollama-main-discollama-1  |   File "/root/.cache/pypoetry/virtualenvs/discollama-_erODJfD-py3.11/lib/python3.11/site-packages/aiohttp/connector.py", line 996, in _wrap_create_connection
discollama-main-discollama-1  |     raise client_error(req.connection_key, exc) from exc
discollama-main-discollama-1  | aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 127.0.0.1:11434 ssl:default [Connect call failed ('127.0.0.1', 11434)]
```

**Comment by Notplying** [comment]
Mb, just gotta change the ollama host to host.docker.internal
